controllers/CalendarController.php
<?php

namespace app\controllers;

use app\models\Event;
use app\models\HD;
use cs\models\Calendar\Maya;
use cs\services\VarDumper;
use cs\web\Exception;
use Yii;
use yii\base\UserException;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\helpers\Url;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\NewsItem;
use cs\base\BaseController;
use DateTime;

class CalendarController extends BaseController
{
    public $layout = 'menu';

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only'  => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow'   => true,
                        'roles'   => ['@'],
                    ],
                ],
            ],
            'verbs'  => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actionTown()
    {
        $term = self::getParam('term');

        return Json::encode(
            HD::query()
                ->select([
                    'gs_hd_town.id',
                    "concat(gs_hd_town.title, ', ',gs_hd.title) as value",
                ])
                ->where(['like', 'gs_hd_town.title', $term])
                ->innerJoin('gs_hd_town', 'gs_hd_town.country_id = gs_hd.id')
                ->all()
        );
    }

    /**
     * Выводит год по лунам
     *
     * @return string
     */
    public function actionMoon()
    {
        return $this->render();
    }

    /**
     * Выводит Оракул дня
     *
     * @return string
     */
    public function actionOrakul()
    {
        return $this->render();
    }

    /**
     * Выводит год по лунам
     *
     * @return string
     */
    public function actionEvents_mandala_festival()
    {
        return $this->render();
    }

    /**
     * Выводит событие
     *
     * @param int $id идентификатор события
     *
     * @return string
     * @throws \cs\web\Exception
     */
    public function actionEvents_item($id)
    {
        $item = Event::find($id);
        if (is_null($item)) {
            throw new Exception('Событие не найдено');
        }

        return $this->render([
            'item' => $item
        ]);
    }

    /**
     * Выводит события
     *
     * @return string
     * @throws \cs\web\Exception
     */
    public function actionEvents()
    {
        return $this->render([
            'items' => Event::query()
                ->limit(12)
                ->where(['>=', 'end_date', gmdate('Ymd')])
                ->orderBy([
                    'start_date' => SORT_ASC,
                ])
                ->all(),
        ]);
    }

    public function actionIndex()
    {
        return $this->redirect(['calendar/orakul']);
    }

    public function actionColkin()
    {
        $days = Maya::colkin();
        $nextDate = new \DateTime($days[20][13]['date']);
        $nextDate->add(new \DateInterval('P1D'));
        $nextDate = $nextDate->format('Y-m-d');

        return $this->render([
            'days'     => $days,
            'nextDate' => $nextDate,
        ]);
    }

    /**
     * Возвращает html для цолькина и дату следующую за ним
     * REQUEST:
     * - date - string - дата в формате 'yyyy-mm-dd'
     *
     * @return string json
     *                [
     *                 'html'     => string - html содержимое цолькина
     *                 'nextDate' => string - дата в формате 'yyyy-mm-dd'
     *                ]
     */
    public function actionColkin_more()
    {
        $date = self::getParam('date');
        $days = Maya::colkin($date);
        $nextDate = new \DateTime($days[20][13]['date']);
        $nextDate->add(new \DateInterval('P1D'));
        $nextDate = $nextDate->format('Y-m-d');

        return self::jsonSuccess(
            [
                'html'     => $this->renderFile('@app/views/calendar/colkin_more.php', [
                    'days' => $days,
                ]),
                'nextDate' => $nextDate,
            ]
        );
    }


    /**
     * Сохраняет дату маянскую для вывода ее потом в шаблоне
     * AJAX
     *
     * REQUEST:
     * - maya - str - json
     * - stamp - int - идентификатор печати от 1
     * - datetime - str - время у пользователя в формате 'yyyy-mm-dd hh:mm:ss'
     * - date - str - '4 апр 2015 г.'
     */
    public function actionSave()
    {
//        self::validateRequestJson([
//            ['required', ['stamp', 'datetime', 'date', 'maya']],
//            ['integer', ['stamp']],
//            ['len', ['datetime'], 19],
//        ]);

        $stamp = self::getParam('stamp');
        $maya = self::getParam('maya');
        $datetime = self::getParam('datetime');
        $date = self::getParam('date');
        Yii::$app->session->open();
        Yii::$app->cache->set(Yii::$app->session->getId() . '/maya', [
            'stamp' => $stamp,
            'date'  => $date,
            'maya'  => $maya,
        ], self::actionSave_getDuration($datetime));

        return self::jsonSuccess();
    }

    public function actionSpyral()
    {
        return $this->render([]);
    }

    public function actionFriends()
    {
        if (Yii::$app->user->isGuest) {
            $options = [];
        } else {
            $options = [
                'me' => [
                    'birth_date' => Yii::$app->user->identity->getField('birth_date')
                ]
            ];
        }

        return $this->render($options);
    }

    /**
     * AJAX
     * Выдает список друзей у которых указана полная дата рождения
     *
     * @return string json
     *                [ 'friends' => [
     *                  [
     *                      'id' => int
     *                      'id' => int
     *                      'id' => int
     *                      'id' => int
     * ], ...
     * ]]
     *
     */
    public function actionFriends_vkontakte()
    {
        /** @var \app\services\authclient\VKontakte $client */
        $client = Yii::$app->authClientCollection->clients['vkontakte'];
        $data = $client->api('friends.get', 'GET', [
            'fields' => [
                'nickname',
                'photo_100',
                'bdate',
            ]
        ]);
        $ret = [];
        foreach($data['response'] as $item) {
            $birthDate = ArrayHelper::getValue($item, 'bdate', '');
            if ($birthDate != '') {
                $arr = explode('.', $birthDate);
                if (count($arr) == 3) {
                    $ret[] = [
                        'id'        => $item['uid'],
                        'name'      => $item['first_name'] . ' ' . $item['last_name'],
                        'avatar'    => $item['photo_100'],
                        'birthDate' => $arr,
                    ];
                }
            }
        }

        return self::jsonSuccess([
            'friends' => $ret,
        ]);
    }

    /**
     * Показывает значение в кеше
     */
    public function actionCache_show()
    {
        Yii::$app->session->open();
        VarDumper::dump(Yii::$app->cache->get(Yii::$app->session->getId() . '/maya'));
    }

    /**
     * Выводит страницу с виджетами
     */
    public function actionWidget()
    {
        return $this->render([]);
    }

    /**
     * 13 Ясных Знаков Пакаль Вотана
     */
    public function actionYasnih_znakov()
    {
        return $this->render([]);
    }

    /**
     * Показывает значение в кеше
     */
    public function actionCache_delete()
    {
        Yii::$app->session->open();
        Yii::$app->cache->delete(Yii::$app->session->getId() . '/maya');

        return self::jsonSuccess();
    }

    /**
     * Возвращает количество секунд оставшееся до завершения суток
     *
     * @param $datetime
     *
     * @return int
     */
    private static function  actionSave_getDuration($datetime)
    {
        $thisDateTime = new DateTime($datetime);
        $thisTime = (int)$thisDateTime->format('U');
        $dayNext = $thisDateTime->add(new \DateInterval('P1D'));
        /** @var string $dayNextString 'yyyy-mm-dd hh:mm:ss' */
        $dayNextString = $dayNext->format('Y-m-d') . '00:00:01';
        $dayNextDateTime = new DateTime($dayNextString);
        $dayNextTime = (int)$dayNextDateTime->format('U');

        return $dayNextTime -  $thisTime;
    }
}

views/calendar/_menu.php
<?php

use yii\helpers\Url;

?>
<div class="col-lg-2 hidden-print">
    <div class="list-group">
        <a href="<?= Url::to(['calendar/colkin']) ?>" class="list-group-item<?php if (Url::to(['calendar/colkin']) == Url::to()) { echo ' active'; } ?>"> Цолькин </a>
        <a href="<?= Url::to(['calendar/moon']) ?>" class="list-group-item<?php if (Url::to(['calendar/moon']) == Url::to()) { echo ' active'; } ?>"> Год (по лунам) </a>
        <a href="<?= Url::to(['calendar/friends']) ?>" class="list-group-item<?php if (Url::to(['calendar/friends']) == Url::to()) { echo ' active'; } ?>"> Друзья </a>
        <a href="<?= Url::to(['calendar/orakul']) ?>" class="list-group-item<?php if (Url::to(['calendar/orakul']) == Url::to()) { echo ' active'; } ?>"> Оракул дня </a>
        <a href="<?= Url::to(['calendar/yasnih_znakov']) ?>" class="list-group-item<?php if (Url::to(['calendar/yasnih_znakov']) == Url::to()) { echo ' active'; } ?>"> Ясные знаки </a>
        <a href="<?= Url::to(['calendar/widget']) ?>" class="list-group-item<?php if (Url::to(['calendar/widget']) == Url::to()) { echo ' active'; } ?>"> Виджеты </a>
    </div>
</div>

views/calendar/colkin.php
<?php
/** @var $this yii\web\View */
/** @var array $days двумерный массив [строка от 1][колонка от 1]
 * [
 * 'ton' => int от 1
 * 'kin' => int от 1
 * 'stamp' => int от 1
 * 'isPortal' => bool
 * 'day' => int
 * 'month' => int
 * 'year' => int
 * ]
 */
use cs\models\Calendar\Maya;
use app\services\GsssHtml;
use yii\helpers\Url;

$this->title = 'Цолькин';

$this->registerJs("$('.js-stamp').tooltip()");

$ajax = Url::to(['calendar/colkin_more']);
$this->registerJs(<<<JS
$('#buttonShow').click(function(){
    $('#buttonShow').addClass('active');
    $('#buttonHide').removeClass('active');
    $('.dates').show();
});
$('#buttonHide').click(function(){
    $('#buttonShow').removeClass('active');
    $('#buttonHide').addClass('active');
    $('.dates').hide();
});

var functionMore = function() {
    var me = $(this);
    ajaxJson({
        url: '{$ajax}',
        data: {
            date: $('#lastDate').html()
        },
        beforeSend: function () {
            me.html($('#ajaxLoader').html());
        },
        success: function(ret) {
            var h = $(ret.html);
            h.find('.js-stamp').tooltip();
            me.parent().append(h);
            me.remove();
            $('#lastDate').html(ret.nextDate);
            $('#more').click(functionMore);
        }
    });
};
$('#more').click(functionMore);
JS
);
$mayaAssetUrl = \Yii::$app->assetManager->getBundle('app\assets\Maya\Asset')->baseUrl;
?>
<div class="container">


    <div class="col-lg-12">
        <h1 class="page-header">Цолькин</h1>
    </div>
    <div id="lastDate" style="display: none"><?= $nextDate ?></div>
    <div id="ajaxLoader" style="display: none"><img style="padding-left: 10px;padding-right: 10px;"
             src="<?= \Yii::$app->assetManager->getBundle(\app\assets\App\Asset::className())->baseUrl ?>/images/ajax-loader.gif"
             id=""></div>



    <div class="col-lg-10">
        <div class="btn-group" role="group" aria-label="Даты">
            <button type="button" class="btn btn-default" id="buttonShow">Показать даты</button>
            <button type="button" class="btn btn-default active" id="buttonHide">Скрыть даты</button>
        </div>
        <?= $this->render('colkin_more', ['days' => $days]) ?>
    </div>
    <?= $this->render('_menu') ?>



</div>

views/calendar/colkin_more.php
<?php
/** @var $this yii\web\View */
/** @var array $days двумерный массив [строка от 1][колонка от 1]
 * [
 * 'ton' => int от 1
 * 'kin' => int от 1
 * 'stamp' => int от 1
 * 'isPortal' => bool
 * 'day' => int
 * 'month' => int
 * 'year' => int
 * ]
 */

use cs\models\Calendar\Maya;
use app\services\GsssHtml;
use yii\helpers\Url;

$mayaAssetUrl = \Yii::$app->assetManager->getBundle('app\assets\Maya\Asset')->baseUrl;

function colorStamp($stamp)
{
    $ost = $stamp % 4;
    $color = ($ost == 0) ? $color = Maya::COLOR_YELLOW : $ost;
    switch ($color) {
        case Maya::COLOR_RED:
            return '#f34035';
            break;
        case Maya::COLOR_WHITE:
            return '#ffffff';
            break;
        case Maya::COLOR_BLUE:
            return '#68b3e2';
            break;
        case Maya::COLOR_YELLOW:
            return '#e9ee62';
            break;
    }
}

?>
<p style="margin-top: 20px;">Цолькин от <u><?= GsssHtml::dateString($days[1][1]['date']) ?></u> до
    <u><?= GsssHtml::dateString($days[20][13]['date']) ?></u></p>
<table border="0" cellspacing="0" cellpading="0" style="margin-right: 10px; margin-bottom: 0px;"
       class="border1px000solid">
    <tbody>
    <?php
    foreach ($days as $row) {
        $day = $row[1];
        ?>
        <tr align="center">
            <td align="center" bgcolor="" height="30" width="40">
                <img
                    class="js-stamp"
                    title="<?= Maya::$stampRows[ $day['stamp'] - 1 ][0] ?>"
                    border="0"
                    alt=""
                    width="23"
                    src="<?= $mayaAssetUrl ?>/images/stamp3/<?= $row[1]['stamp'] ?>.gif">
            </td>
            <?php
            foreach ($row as $day) {
                ?>
                <td align="center"
                    bgcolor="<?= ($day['isPortal']) ? 'green' : (($day['kin'] > 120 and $day['kin'] <= 140) ? '#dcdcdc' : colorStamp($day['stamp'])) ?>"
                    height="30"
                    width="40"
                    <?= ($day['isToday'] == 1) ? "style='border: 3px solid red'" : ''  ?>
                    >

                    <img
                        title="<?= GsssHtml::dateString($day['date']) ?>"
                        class="js-stamp"
                        border="0"
                        alt=""
                        width="23"
                        src="<?= $mayaAssetUrl ?>/images/ton/<?= $day['ton'] ?>.gif"
                        ><br>
                    <?= $day['kin'] ?>

                </td>
            <?php
            }
            ?>
        </tr>
        <tr align="center" class="dates" style="display: none;">
            <td align="center" bgcolor="" height="30" width="40">
            </td>
            <?php
            foreach ($row as $day) {
                ?>
                <td align="center"
                    bgcolor="<?= ($day['isPortal']) ? 'green' : (($day['kin'] > 120 and $day['kin'] <= 140) ? '#dcdcdc' : colorStamp($day['stamp'])) ?>"
                    height="30"
                    width="40"
                    >
                    <span
                        title="<?= GsssHtml::dateString($day['date']) ?>"
                        class="js-stamp"
                        ><?= $day['day'] ?>.<?= $day['month'] ?></span>
                </td>
            <?php
            }
            ?>
        </tr>
    <?php
    }
    ?>
    </tbody>
</table>
<button type="button" class="btn btn-default hidden-print" id="more" style="margin-top: 40px;">Показать еще</button>

views/calendar/events.php
<?php
/** @var array $items */
/** @var $this yii\web\View */

use cs\helpers\Html;
use app\services\GsssHtml;
use cs\models\Calendar\Maya;

$this->title = 'События на Планете Земля';

?>
<div class="container">

    <div class="col-lg-12">
        <h1 class="page-header">События</h1>
    </div>

    <?php if (count($items) > 0) { ?>
        <?php foreach ($items as $event) {
            $link = $event['link'] . '';
            if ($link == '') {
                $link = '/events/' . $event['id'];
            }
            ?>
            <div class="col-lg-4">
                <h3 style="height: 70px;"><?= $event['name'] ?></h3>

                <p><?= $event['date'] ?></p>

                <p style="margin-bottom: 0px;padding-bottom: 0px;">
                    <a href="<?= $link ?>">
                        <img
                            src="<?= $event['image'] ?>"
                            width="100%"
                            alt=""
                            class="thumbnail"
                            >
                    </a>
                </p>
                <!--                    <table>-->
                <!--                        <tr>-->
                <!--                            <td style='font-family: "courier new", "times new roman", monospace; font-size: 8pt;text-align: center;'>-->
                <!--                                12-->
                <!--                            </td>-->
                <!--                            <td style='font-family: "courier new", "times new roman", monospace; font-size: 8pt;text-align: center;'>-->
                <!--                                13-->
                <!--                            </td>-->
                <!--                            <td style='font-family: "courier new", "times new roman", monospace; font-size: 8pt;text-align: center;'>-->
                <!---->
                <!--                            </td>-->
                <!--                            <td style='font-family: "courier new", "times new roman", monospace; font-size: 8pt;text-align: center;'>-->
                <!--                                23-->
                <!--                            </td>-->
                <!--                            <td style='font-family: "courier new", "times new roman", monospace; font-size: 8pt;text-align: center;'>-->
                <!--                                24-->
                <!--                            </td>-->
                <!--                        </tr>-->
                <!--                        <tr>-->
                <!--                            <td>-->
                <!--                                <img src="/assets/57410080/images/ton/12.gif" width="20">-->
                <!--                            </td>-->
                <!--                            <td>-->
                <!--                                <img src="/assets/57410080/images/ton/12.gif" width="20">-->
                <!--                            </td>-->
                <!--                            <td style="padding-right: 10px;padding-left: 5px;">-->
                <!--                                <img src="/assets/57410080/images/ton/3.gif" width="20">-->
                <!--                            </td>-->
                <!--                            <td>-->
                <!--                                <img src="/assets/57410080/images/ton/12.gif" width="20">-->
                <!--                            </td>-->
                <!--                            <td>-->
                <!---->
                <!--                                <img src="/assets/57410080/images/ton/12.gif" width="20">-->
                <!--                            </td>-->
                <!--                        </tr>-->
                <!--                        <tr>-->
                <!--                            <td style="padding-right: 5px;">-->
                <!--                                <img src="/assets/57410080/images/stamp3/12.gif" width="20">-->
                <!--                            </td>-->
                <!--                            <td style="padding-right: 5px;">-->
                <!--                                <img src="/assets/57410080/images/stamp3/12.gif" width="20">-->
                <!--                            </td>-->
                <!--                            <td>-->
                <!--                            </td>-->
                <!--                            <td style="padding-right: 5px;">-->
                <!--                                <img src="/assets/57410080/images/stamp3/12.gif" width="20">-->
                <!---->
                <!--                            </td>-->
                <!--                            <td>-->
                <!---->
                <!--                                <img src="/assets/57410080/images/stamp3/12.gif" width="20" id="dd1">-->
                <!---->
                <!--                                <div style="position: absolute; top: 508px;left: 136px; z-index: 999; ">-->
                <!--                                    <img src="/assets/57410080/images/stamp3/13.gif" width="10" alt="dddd" onmouseover="" style="border-radius: 5px;">-->
                <!--                                </div>-->
                <!--                            </td>-->
                <!--                        </tr>-->
                <!--                    </table>-->
            </div>
        <?php } ?>
    <?php } ?>

    <div class="col-lg-12">
        <hr>
        <?= $this->render('../blocks/share', [
            'image'       => \yii\helpers\Url::to('/images/calendar/events/header.jpg', true),
            'url'         => \yii\helpers\Url::current([], true),
            'title'       => $this->title,
            'description' => 'Предстоящие события на Планете Земля',
        ]) ?>
    </div>


</div>

views/calendar/events_item.php
<?php
/** @var $this yii\web\View */
/** @var \app\models\Event $item
 */

use cs\models\Calendar\Maya;
use app\services\GsssHtml;
use yii\helpers\Url;

$this->title = $item->getField('name');

?>
<style>
    .download-section {
        width: 100%;
        padding: 50px 0;
        color: #fff;
        background: url('<?= \cs\Widget\FileUpload3\FileUpload::getOriginal($item->getField('image')) ?>') no-repeat center center scroll;
        background-color: #000;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        background-size: cover;
        -o-background-size: cover;
    }
</style>
<section id="contact" class="content-section text-center" style="">
    <div class="download-section" style="
    border-bottom: 1px solid #87aad0;
    border-top: 1px solid #87aad0;
    height: 450px;
    ">
        <div class="container">
            <div class="col-lg-8 col-lg-offset-2" style="color: #000000">

            </div>
        </div>
    </div>
</section>
<div class="container" style="padding-top: 0px;">
    <div class="col-lg-12">
        <h1 class="page-header text-center"><?= $this->title ?></h1>
    </div>

    <div class="col-lg-12">
        <div class="col-lg-10 col-lg-offset-1">
            <?= $item->getField('content') ?>
            <hr>
            <?= $this->render('../blocks/share', [
                'image'       => ($item->getField('image') != '')? Url::to(\cs\Widget\FileUpload2\FileUpload::getOriginal($item->getField('image')), true) : '' ,
                'url'         => Url::current([], true),
                'title'       => $item->getField('name'),
                'description' => trim(\cs\services\Str::sub(strip_tags($item->getField('content')), 0, 200)),
            ]) ?>
        </div>

    </div>

</div>

views/calendar/friends.php
<?php
/** @var array $days */
/** @var \Yii $app */
/** @var $this yii\web\View */

/** @var $me array[
 *  'birth_date' '2018-12-12'
 * ] будет присутствовать если пользователь авторизован
 */

use cs\helpers\Html;
use app\services\GsssHtml;
use cs\models\Calendar\Maya;
use yii\web\View;
use yii\authclient\widgets\AuthChoice;

$this->title = 'Календарь';

$this->registerJsFile('/js/pages/calendar/friends.js', [
    'depends' => [
        'app\assets\Maya\Asset',
        'yii\web\JqueryAsset',
    ]
]);

$mayaAssetUrl = Yii::$app->assetManager->getBundle('app\assets\Maya\Asset')->baseUrl;
$this->registerJs("var MayaAssetUrl='{$mayaAssetUrl}'", View::POS_HEAD);

$layoutAssetUrl = Yii::$app->assetManager->getBundle('app\assets\LayoutMenu\Asset')->baseUrl;
$this->registerJs("var LayoutAssetUrl='{$layoutAssetUrl}';", View::POS_HEAD);

?>
<div class="container">

    <div class="col-lg-12">
        <h1 class="page-header">Друзья</h1>
    </div>

    <div class="col-lg-10">
        <?php if (!\Yii::$app->user->isGuest) { ?>
            <div class="hide" id="meBirthDate"><?= $me['birth_date'] ?></div>
        <?php } ?>

        <?php
        if (\Yii::$app->authClientCollection->getClient('vkontakte')->isAuthorize()) { ?>
            <button class="btn btn-default" id="buttonVkontakte">Вконтакте</button>
        <?php } else { ?>

            <p>Извините вы не авторизованы через Vk, пожалуйста зайтите через Vk</p>
            <?php $authAuthChoice = AuthChoice::begin([
                'baseAuthUrl' => ['auth/auth']
            ]); ?>
            <?php foreach ($authAuthChoice->getClients() as $client) {
                /** @var \yii\authclient\ClientInterface $client  */
                if ($client instanceof \app\services\authclient\VKontakte) {
                    ?>
                    <li><?php $authAuthChoice->clientLink($client) ?></li>
                <?php  } ?>
            <?php  } ?>
            <?php AuthChoice::end(); ?>
        <?php } ?>

        <div id="friends" class="col-lg-8">

        </div>
    </div>
    <?= $this->render('_menu') ?>


</div>

views/calendar/moon.php
<?php
/** @var array $days */
/** @var $this yii\web\View */

use cs\helpers\Html;
use app\services\GsssHtml;
use cs\models\Calendar\Maya;

$this->title = 'Календарь';

$this->registerJsFile('/js/pages/calendar/moon.js', [
        'depends' => [
            'app\assets\LayoutMenu\Asset',
            'app\assets\Maya\Asset',
            'app\assets\ScrollTo',
            'yii\web\JqueryAsset',
            'app\assets\Encoder\Asset',
        ]
    ]);
$mayaAssetUrl = \Yii::$app->assetManager->getBundle('app\assets\Maya\Asset')->baseUrl;
$pathLayoutMenu = \Yii::$app->assetManager->getBundle('app\assets\LayoutMenu\Asset')->baseUrl;
$this->registerJs("$('.js-stamp').tooltip();");
$this->registerJs("Moon.init('{$mayaAssetUrl}');");
$this->registerJs("var pathLayoutMenu = '{$pathLayoutMenu}';", \yii\web\View::POS_HEAD);

$dayInWeek = date('N') + 1;
if ($dayInWeek == 1) {
    $day = 0;
}
else {
    $day = 7 - ($dayInWeek - 1);
}

$dayWeekList = [
    1 => 'сб',
    2 => 'вс',
    3 => 'пн',
    4 => 'вт',
    5 => 'ср',
    6 => 'чт',
    7 => 'пт',
];

?>
<div class="container">

    <div class="col-lg-12">
        <h1 class="page-header">Календарь</h1>
    </div>


    <style>
        .dateGrisha {
            padding-left: 5px;
        }

        .portal {
            padding-left: 5px;
            text-decoration: underline;
        }

        .kin {
            color: #cccccc;
        }

        .calendar {
            margin-bottom: 40px;
        }

        .calendar td {
            height: 100px;
            text-align: left;
            vertical-align: middle;
            width: 130px;
            border-bottom: 1px solid #cccccc;
            padding: 0px 0px 0px 10px;
        }

        .calendar tr.red td {
            background-color: #fae0df;
        }

        .calendar tr.blue td {
            background-color: #d8eaf4;
        }

        .calendar tr.yellow td {
            background-color: #fef9db;
        }

        .calendar th {
            padding: 10px 10px 10px 20px;
            text-align: left;
            border-bottom: 1px solid #cccccc;
            font-weight: normal;
        }

        .calendar th img {
            height: 20px;
        }

        #main-content {
            margin-bottom: 80px;
        }
    </style>

    <div id="lastDay" class="hide"></div>
    <div class="col-lg-10" id="main-content">

        <p><img src="" id="ajax-loader"></p>

        <table class="calendar">

        </table>

        <button class="btn btn-default" id="buttonNextYear">Следующий год</button>

        <hr>
        <?= $this->render('../blocks/share', [
            'image'       => \yii\helpers\Url::to(Yii::$app->getAssetManager()->getBundle('app\assets\Maya\Asset')->get('/images/stamp2/9.jpg') , true),
            'url'         => \yii\helpers\Url::current([], true),
            'title'       => $this->title,
            'description' => $this->title,
        ]) ?>

    </div>
    <?= $this->render('_menu') ?>



    <!-- dialog itself, mfp-hide class is required to make dialog hidden -->
    <div id="small-dialog" class="zoom-anim-dialog mfp-hide">
        <h1>Dialog example</h1>
        <p>This is dummy copy. It is not meant to be read. It has been placed here solely to demonstrate the look and feel of finished, typeset text. Only for show. He who searches for meaning here will be sorely disappointed.</p>
    </div>
</div>

views/calendar/widget.php
<?php
/** @var $this yii\web\View */

use cs\helpers\Html;
use app\services\GsssHtml;
use cs\models\Calendar\Maya;

$this->title = 'Виджеты для календаря Майя';

$this->registerJs("var pathZClip = '".\Yii::$app->assetManager->getBundle('cs\assets\ZClip\Asset')->baseUrl."';", \yii\web\View::POS_HEAD);
$this->registerJs(<<<JS
    $(".buttonCopy1").zclip({
        path: pathZClip + '/ZeroClipboard.swf',
        copy: $('#textCode1').val(),
        beforeCopy: function () {
        },
        afterCopy: function () {
            infoWindow('Скопировано');
        }
    });
JS
);
$mayaAssetUrl = \Yii::$app->assetManager->getBundle('app\assets\Maya\Asset')->baseUrl;

?>
<div class="container">

    <div class="col-lg-12">
        <h1 class="page-header"><?= $this->title ?></h1>
    </div>

    <div class="col-lg-10">
        <div class="col-lg-1">
            1.
        </div>
        <div class="col-lg-3">
            <script src='/js/widget/maya-today.js'></script>
        </div>
        <div class="col-lg-8">
            <textarea rows="5"
                      style="width: 100%;"
                      id="textCode1"
                ><?= Html::encode("<script src='//" . $_SERVER['SERVER_NAME'] . "/js/widget/maya-today.js'></script>") ?></textarea>
            <button class="btn btn-default btn-sm buttonCopy1" id="copy1">Копировать в буфер</button>
        </div>
    </div>
    <?= $this->render('_menu') ?>

</div>